# 0. Prerequisites

1. Install git
2. clone PEPS
3. Install PEPS depenendicies

In [1]:
## Install Git
import sys
!sudo yum -y install git

Loaded plugins: priorities, update-motd, upgrade-helper
13 packages excluded due to repository priority protections
Resolving Dependencies
--> Running transaction check
---> Package git.x86_64 0:2.14.6-1.61.amzn1 will be installed
--> Processing Dependency: perl-Git = 2.14.6-1.61.amzn1 for package: git-2.14.6-1.61.amzn1.x86_64
--> Processing Dependency: perl(Term::ReadKey) for package: git-2.14.6-1.61.amzn1.x86_64
--> Processing Dependency: perl(Git::I18N) for package: git-2.14.6-1.61.amzn1.x86_64
--> Processing Dependency: perl(Git) for package: git-2.14.6-1.61.amzn1.x86_64
--> Processing Dependency: perl(Error) for package: git-2.14.6-1.61.amzn1.x86_64
--> Running transaction check
---> Package perl-Error.noarch 1:0.17020-2.9.amzn1 will be installed
---> Package perl-Git.noarch 0:2.14.6-1.61.amzn1 will be installed
---> Package perl-TermReadKey.x86_64 0:2.30-20.9.amzn1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package              Arch       Version                 Repository        Size
================================================================================
Installing:
 git                  x86_64     2.14.6-1.61.amzn1       amzn-updates      12 M
Installing for dependencies:
 perl-Error           noarch     1:0.17020-2.9.amzn1     amzn-main         33 k
 perl-Git             noarch     2.14.6-1.61.amzn1       amzn-updates      69 k
 perl-TermReadKey     x86_64     2.30-20.9.amzn1         amzn-main         33 k

Transaction Summary
================================================================================
Install  1 Package (+3 Dependent packages)

Total download size: 12 M
Installed size: 29 M
Downloading packages:
(1/4): perl-Error-0.17020-2.9.amzn1.noarch.rpm             |  33 kB   00:00
(2/4): perl-Git-2.14.6-1.61.amzn1.noarch.rpm               |  69 kB   00:00
(3/4): perl-TermReadKey-2.30-20.9.amzn1.x86_64.rpm         |  33 kB   00:00
(4/4): git-2.14.6-1.61.amzn1.x86_64.rpm                    |  12 MB   00:00
--------------------------------------------------------------------------------
Total                                               51 MB/s |  12 MB  00:00
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : 1:perl-Error-0.17020-2.9.amzn1.noarch                        1/4
  Installing : perl-TermReadKey-2.30-20.9.amzn1.x86_64                      2/4
  Installing : git-2.14.6-1.61.amzn1.x86_64                                 3/4
  Installing : perl-Git-2.14.6-1.61.amzn1.noarch                            4/4
  Verifying  : 1:perl-Error-0.17020-2.9.amzn1.noarch                        1/4
  Verifying  : git-2.14.6-1.61.amzn1.x86_64                                 2/4
  Verifying  : perl-TermReadKey-2.30-20.9.amzn1.x86_64                      3/4
  Verifying  : perl-Git-2.14.6-1.61.amzn1.noarch                            4/4

Installed:
  git.x86_64 0:2.14.6-1.61.amzn1

Dependency Installed:
  perl-Error.noarch 1:0.17020-2.9.amzn1     perl-Git.noarch 0:2.14.6-1.61.amzn1
  perl-TermReadKey.x86_64 0:2.30-20.9.amzn1

Complete!

In [2]:
#clone PEPS repo
!git clone https://github.com/aehrc/PEPS.git

Cloning into 'PEPS'...
remote: Enumerating objects: 45, done.
remote: Total 45 (delta 0), reused 0 (delta 0), pack-reused 45
Unpacking objects: 100% (45/45), done.

In [3]:
#Install dependency https://github.com/dceoy/pdbio
!{sys.executable} -m pip install -U https://github.com/dceoy/pdbio/archive/master.tar.gz
!{sys.executable} -m pip install -U scikit-learn

Collecting https://github.com/dceoy/pdbio/archive/master.tar.gz
  Downloading https://github.com/dceoy/pdbio/archive/master.tar.gz
     \ 20kB 26.7MB/s
Collecting docopt (from pdbio==0.4.2)
  Downloading https://files.pythonhosted.org/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz
Requirement already satisfied, skipping upgrade: pandas in ./biospark/lib/python3.6/site-packages (from pdbio==0.4.2) (0.23.4)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.5.0 in ./biospark/lib/python3.6/site-packages (from pandas->pdbio==0.4.2) (2.8.1)
Requirement already satisfied, skipping upgrade: pytz>=2011k in ./biospark/lib/python3.6/site-packages (from pandas->pdbio==0.4.2) (2019.3)
Requirement already satisfied, skipping upgrade: numpy>=1.9.0 in ./biospark/lib/python3.6/site-packages (from pandas->pdbio==0.4.2) (1.18.1)
Requirement already satisfied, skipping upgrade: six>=1.5 in ./biospark/lib/python3.6/site-packages (from python-dateutil>=2.5.0->pandas->pdbio==0.4.2) (1.14.0)
Building wheels for collected packages: pdbio, docopt
  Building wheel for pdbio (setup.py) ... done
  Stored in directory: /mnt/tmp/pip-ephem-wheel-cache-mdtr4nb7/wheels/e5/5a/c7/0ecdb2f03a7e8c3b384bf01a5e07d62a8dfa8920085abcaa06
  Building wheel for docopt (setup.py) ... done
  Stored in directory: /home/hadoop/.cache/pip/wheels/9b/04/dd/7daf4150b6d9b12949298737de9431a324d4b797ffd63f526e
Successfully built pdbio docopt
Installing collected packages: docopt, pdbio
Successfully installed docopt-0.6.2 pdbio-0.4.2
Collecting scikit-learn
  Downloading https://files.pythonhosted.org/packages/d1/48/e9fa9e252abcd1447eff6f9257636af31758a6e46fd5ce5d3c879f6907cb/scikit_learn-0.22.1-cp36-cp36m-manylinux1_x86_64.whl (7.0MB)
     |████████████████████████████████| 7.1MB 45.4MB/s eta 0:00:01
Requirement already satisfied, skipping upgrade: numpy>=1.11.0 in ./biospark/lib/python3.6/site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied, skipping upgrade: scipy>=0.17.0 in ./biospark/lib/python3.6/site-packages (from scikit-learn) (1.3.3)
Collecting joblib>=0.11 (from scikit-learn)
  Downloading https://files.pythonhosted.org/packages/28/5c/cf6a2b65a321c4a209efcdf64c2689efae2cb62661f8f6f4bb28547cf1bf/joblib-0.14.1-py2.py3-none-any.whl (294kB)
     |████████████████████████████████| 296kB 51.2MB/s eta 0:00:01
Installing collected packages: joblib, scikit-learn
Successfully installed joblib-0.14.1 scikit-learn-0.22.1

In [219]:
# https://github.com/changyaochen/rbo
!sudo {sys.executable} -m pip install -e git+https://github.com/changyaochen/rbo.git@master#egg=rbo
# (might have to install this outside of the jupyter notebook...)
# Do I really need this??
#!{sys.executable} -m pip install --user pipenv
#!{sys.executable} -m pipenv install -e git+https://github.com/changyaochen/rbo.git@master#egg=rbo

Obtaining rbo from git+https://github.com/changyaochen/rbo.git@master#egg=rbo
  Updating ./src/rbo clone (to revision master)
  Running command git fetch -q --tags
  Running command git reset --hard -q 2b2ff7b24534f342a5153573bf384c06317ec2de
Requirement already satisfied: numpy in ./biospark/lib/python3.6/site-packages (from rbo) (1.18.1)
Installing collected packages: rbo
  Found existing installation: rbo 0.1
    Uninstalling rbo-0.1:
      Successfully uninstalled rbo-0.1
  Running setup.py develop for rbo
Successfully installed rbo

# 1. Helper scripts

In [22]:
# Helper function to create new config file

import json
import os

def newConfigFile(outputPrefix,inputPrefix,outfile,v1,v2,v3,v4,v5):
    with open("PEPS/SampleData/config-small.json", 'r') as f:
        config = json.load(f)

        config['inputType']='csv'
        config['outputPrefix']=outputPrefix
        config['inputPrefix']=inputPrefix
        config['variables'][0]['numVar']=v1
        config['variables'][1]['numVar']=v2
        config['variables'][2]['numVar']=v3
        config['variables'][3]['numVar']=v4
        config['variables'][4]['numVar']=v5

    os.makedirs(os.path.dirname(outfile), exist_ok=True)
    with open(outfile+".json", 'w') as outfile:
        json.dump(config, outfile, sort_keys=True, indent=4)

# Set up run

In [23]:
PEPSINPUT="/home/hadoop/PEPS/1000Genomes/all-snps-header"
LOCALDIR="/home/hadoop/PEPS/Test"

In [5]:
!gunzip $PEPSINPUT".csv.gz"
# just renaming and unzipping does not seem to work 
#!mv /home/hadoop/PEPS/1000Genomes/all-snps.vcf.bgz /home/hadoop/PEPS/1000Genomes/all-snps.vcf.gz
#!gunzip /home/hadoop/PEPS/1000Genomes/all-snps.vcf.gz

In [212]:
# input data 
#newConfigFile("PEPS/SampleData/output-small",
#              "PEPS/SampleData/input-small",
#              "PEPS/SampleData/config-small-mod",
#              12,3,3,6,10)

#v1=11; v2=3; v3=3; v4=6; v5=10
#v1=1; v2=3; v3=3; v4=6; v5=20
#v1=20; v2=3; v3=3; v4=6; v5=1
#v1=2; v2=4; v3=6; v4=8; v5=10
#v1=10; v2=8; v3=6; v4=4; v5=2 <- OK results
v1=5; v2=4; v3=3; v4=2; v5=1


"_"+"_".join(str(e) for e in [v1,v2,v3,v4,v5])

BASE="all-snps-header_"+"_".join(str(e) for e in [v1,v2,v3,v4,v5])

newConfigFile(LOCALDIR+"/"+BASE,
              PEPSINPUT,
              LOCALDIR+"/"+BASE,
              v1,v2,v3,v4,v5)

In [213]:
!{sys.executable} PEPS/PEPS.py $LOCALDIR/$BASE".json"

========== Configuration >>>
{'dumpCSV': True,
 'inputPrefix': '/home/hadoop/PEPS/1000Genomes/all-snps-header',
 'inputType': 'csv',
 'maxOrder': 5,
 'numLoop': 1,
 'numSnpsNeeded': 35,
 'numTree': 500,
 'numVariables': 15,
 'outputPrefix': '/home/hadoop/PEPS/Test/all-snps-header_5_4_3_2_1',
 'pvalueThr': 0.001,
 'shuffleSnps': True,
 'variables': [{'numSNPs': 5, 'numSnpsInVar': 1, 'numVar': 5},
               {'numSNPs': 8, 'numSnpsInVar': 2, 'numVar': 4},
               {'numSNPs': 9, 'numSnpsInVar': 3, 'numVar': 3},
               {'numSNPs': 8, 'numSnpsInVar': 4, 'numVar': 2},
               {'numSNPs': 5, 'numSnpsInVar': 5, 'numVar': 1}]}
============================
Number of SNPs in the input file:  17373
Number of SNPs needed:  35
There are enough SNPs in the input file
number of sample 2504
number of snp 17373
loop 1
Done
Number of Variables:  15
Number of Truth Variables:  9
Number of SNPs used to form Variables:  35
Number of Truth SNPs (SNPs in Truth Variables):  28
PEPS/PEPS.py:465: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  snpDataTruth['lbl'] = varGT['lbl']
PEPS/PEPS.py:466: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  snpDataVar['lbl'] = varGT['lbl']
AUC Truth SNPs            :  0.7295136884637585
AUC All SNPs in Variables :  0.7374404761904763
AUC All SNPs in input file:  0.5520164609053497

# results

Running twice to get a little bit of a feeling for the spread

## balanced

```
v1=10; v2=8; v3=6; v4=4; v5=2
AUC Truth SNPs            :  0.6566427686316161
AUC All SNPs in Variables :  0.6886058068006493
AUC All SNPs in input file:  0.5542574656981435

AUC Truth SNPs            :  0.6848957481825414
AUC All SNPs in Variables :  0.6316260899594233
AUC All SNPs in input file:  0.5071729908633228

v1=5; v2=4; v3=3; v4=2; v5=1
AUC Truth SNPs            :  0.7295136884637585
AUC All SNPs in Variables :  0.7374404761904763
AUC All SNPs in input file:  0.5520164609053497


```

```
v1=11; v2=3; v3=3; v4=6; v5=10
AUC Truth SNPs            :  0.5945935235507246
AUC All SNPs in Variables :  0.5879051508157267
AUC All SNPs in input file:  0.48481233847087507

AUC Truth SNPs            :  0.5866592799049621
AUC All SNPs in Variables :  0.5947047619047621
AUC All SNPs in input file:  0.5366248137901681
```
____________________________________________________


## weight towards multiple variants

```
v1=1; v2=3; v3=3; v4=6; v5=20
AUC Truth SNPs            :  0.5520690460950756
AUC All SNPs in Variables :  0.544824642385618
AUC All SNPs in input file:  0.5093466424682396

AUC Truth SNPs            :  0.531187248995984
AUC All SNPs in Variables :  0.5479636094361579
AUC All SNPs in input file:  0.45317957451721846
```
____________________________________________________


## weight towards individual variants

```
v1=20; v2=3; v3=3; v4=6; v5=1

AUC Truth SNPs            :  0.6719735789816652
AUC All SNPs in Variables :  0.6794628877442193
AUC All SNPs in input file:  0.5286143098837526

AUC Truth SNPs            :  0.6997608799617409
AUC All SNPs in Variables :  0.6931490747193992
AUC All SNPs in input file:  0.5773875449334499

```

# Running VariantSpark

In [214]:
#BASE="all-snps-header_10_8_6_4_2"
BASE="all-snps-header_5_4_3_2_1"
DATA1000GENOMES="subset.3.withTruth.vcf.bgz" #3 for 0.5M snps and 2 for 5M snps
S3DIR="s3://variant-spark/GigaScience/Data"

In [215]:
#upload the newly created files
!aws s3 cp $LOCALDIR"/"$BASE".pheno.csv"      $S3DIR"/PEPS/"$BASE".pheno.csv"
# also upload truth data for savekeeping
!aws s3 cp $LOCALDIR"/"$BASE".varDataTruth.csv"      $S3DIR"/PEPS/"$BASE".varDataTruth.csv" 
!aws s3 cp $LOCALDIR"/"$BASE".TruthSNP.csv"      $S3DIR"/PEPS/"$BASE".TruthSNP.csv"

upload: PEPS/Test/all-snps-header_5_4_3_2_1.pheno.csv to s3://variant-spark/GigaScience/Data/PEPS/all-snps-header_5_4_3_2_1.pheno.csv
upload: PEPS/Test/all-snps-header_5_4_3_2_1.varDataTruth.csv to s3://variant-spark/GigaScience/Data/PEPS/all-snps-header_5_4_3_2_1.varDataTruth.csv
upload: PEPS/Test/all-snps-header_5_4_3_2_1.TruthSNP.csv to s3://variant-spark/GigaScience/Data/PEPS/all-snps-header_5_4_3_2_1.TruthSNP.csv

In [216]:
!biospark/bin/spark-submit --deploy-mode client --class au.csiro.variantspark.cli.VariantSparkApp \
/home/hadoop/biospark/lib/python3.6/site-packages/varspark/jars/variant-spark_2.11-0.3.0-SNAPSHOT-all.jar \
importance \
-if $S3DIR"/1000Genomes/"$DATA1000GENOMES \
-it vcf \
-ff $S3DIR"/PEPS/"$BASE".pheno.csv" \
-fc lbl \
-of $S3DIR"/PEPS/"$BASE".vs.csv" \
-on 100000 -rn 500 -rmtf 0.1 -rbs 100 -ro -ovn raw -sr 13 -od

20/01/20 04:52:24 INFO ImportanceCmd: Running with params: au.csiro.variantspark.cli.ImportanceCmd@73d62b5[featuresFile=s3://variant-spark/GigaScience/Data/PEPS/all-snps-header_5_4_3_2_1.pheno.csv,featureColumn=lbl,outputFile=s3://variant-spark/GigaScience/Data/PEPS/all-snps-header_5_4_3_2_1.vs.csv,nVariables=100000,includeData=true,randomSeed=13,modelFile=<null>,modelFileFormat=java,nTrees=500,rfMTry=-1,rfMTryFraction=0.1,rfEstimateOob=true,rfRandomizeEqual=false,rfSubsampleFraction=NaN,rfSampleNoReplacement=false,rfBatchSize=64,rfMaxDepth=2147483647,rfMinNodeSize=1,correctImportance=false,airRandomSeed=0,nOuputParitions=0,outputNormalization=raw,formats=org.json4s.DefaultFormats$@63917fe1,inputFile=s3://variant-spark/GigaScience/Data/1000Genomes/subset.3.withTruth.vcf.bgz,inputType=vcf,inputOptions=<null>,inputJSON=<null>,featureSource=<null>,beVerbose=false,beSilent=false,sparkPar=0,conf=org.apache.spark.SparkConf@720f56e2,spark=org.apache.spark.sql.SparkSession@677349fb,sc=org.apache.spark.SparkContext@4466cf5d,sqlContext=<null>]
Finding  100000  most important features using random forest
Loading header from VCF file: s3://variant-spark/GigaScience/Data/1000Genomes/subset.3.withTruth.vcf.bgz
Loaded rows: [HG00096,HG00097,HG00099,...,NA21142,NA21143,NA21144] total: 2504
Loaded variables: [1_15820_G_T,1_54165_G_C,1_55416_G_A,1_62017_A_G,1_62777_A_T,1_63268_T_C,...] total: 517729, took: 111.857
Loading labels from: s3://variant-spark/GigaScience/Data/PEPS/all-snps-header_5_4_3_2_1.pheno.csv, column: lbl
20/01/20 04:54:16 INFO S3NativeFileSystem: Opening 's3://variant-spark/GigaScience/Data/PEPS/all-snps-header_5_4_3_2_1.pheno.csv' for reading
Loaded labels: [1,0,1,...,0,0,1] total: 2504
Training random forest with trees: 500 (batch size:  64)
Random seed is: 13
RF Params: au.csiro.variantspark.algo.RandomForestParams@17f7a1af[oob=true,nTryFraction=0.1,bootstrap=true,subsample=1.0,randomizeEquality=true,seed=13,maxDepth=2147483647,minNodeSize=1,correctImpurity=false,airRandomSeed=0]
RF Params mTry: 51772
Finished trees: 64, current oobError: 0.43570287539936103, totalTime: 281.761 s, avg timePerTree: 4.402515625 s
Last build trees: 64, time: 281761 ms, timePerTree: 4402 ms
Finished trees: 128, current oobError: 0.4193290734824281, totalTime: 575.857 s, avg timePerTree: 4.4988828125 s
Last build trees: 64, time: 294096 ms, timePerTree: 4595 ms
Finished trees: 192, current oobError: 0.420926517571885, totalTime: 869.11 s, avg timePerTree: 4.526614583333333 s
Last build trees: 64, time: 293253 ms, timePerTree: 4582 ms
Finished trees: 256, current oobError: 0.41333865814696485, totalTime: 1170.011 s, avg timePerTree: 4.57035546875 s
Last build trees: 64, time: 300901 ms, timePerTree: 4701 ms
Finished trees: 320, current oobError: 0.41293929712460065, totalTime: 1457.788 s, avg timePerTree: 4.5555875 s
Last build trees: 64, time: 287777 ms, timePerTree: 4496 ms
Finished trees: 384, current oobError: 0.4145367412140575, totalTime: 1751.504 s, avg timePerTree: 4.561208333333333 s
Last build trees: 64, time: 293716 ms, timePerTree: 4589 ms
Finished trees: 448, current oobError: 0.40934504792332266, totalTime: 2055.898 s, avg timePerTree: 4.589058035714285 s
Last build trees: 64, time: 304394 ms, timePerTree: 4756 ms
Finished trees: 500, current oobError: 0.41014376996805113, totalTime: 2298.625 s, avg timePerTree: 4.59725 s
Last build trees: 52, time: 242727 ms, timePerTree: 4667 ms
Random forest oob accuracy: 0.41014376996805113, took: 2298.827 s
Variable importance preview
21_19506651_G_A: 5.956927997557528
9_79469334_T_C: 4.6590365117707675
12_76362129_C_T: 0.6558799842524119
12_20412031_A_T: 0.652729976413693
7_71185237_G_A: 0.6455791846493515
8_4075279_G_A: 0.6291522904675982
5_11016111_G_T: 0.5387878273072324
20/01/20 05:34:14 INFO MultipartUploadOutputStream: uploadPart: partNum 1 of 's3://variant-spark/GigaScience/Data/PEPS/all-snps-header_5_4_3_2_1.vs.csv' from local file '/mnt/s3/emrfs-4403151201893558791/0000000000', 134217728 bytes in 1837 ms, md5: sz4mLSXKv3640+oMNz1Fgw== md5hex: b33e262d25cabf7eb8d3ea0c373d4583
20/01/20 05:35:16 INFO MultipartUploadOutputStream: uploadPart: partNum 2 of 's3://variant-spark/GigaScience/Data/PEPS/all-snps-header_5_4_3_2_1.vs.csv' from local file '/mnt1/s3/emrfs-2387768637491030874/0000000001', 134217728 bytes in 2071 ms, md5: wuvNKHzYRNJeLs8rcaLf4g== md5hex: c2ebcd287cd844d25e2ecf2b71a2dfe2
20/01/20 05:35:36 INFO MultipartUploadOutputStream: close closed:false s3://variant-spark/GigaScience/Data/PEPS/all-snps-header_5_4_3_2_1.vs.csv
20/01/20 05:35:37 INFO MultipartUploadOutputStream: uploadPart: partNum 3 of 's3://variant-spark/GigaScience/Data/PEPS/all-snps-header_5_4_3_2_1.vs.csv' from local file '/mnt2/s3/emrfs-5128550870740535032/0000000002', 44682578 bytes in 687 ms, md5: OHI7fT4DQzbdDM6PHArItQ== md5hex: 38723b7d3e034336dd0cce8f1c0ac8b5
20/01/20 05:35:37 INFO DefaultMultipartUploadDispatcher: Completed multipart upload of 3 parts 313118034 bytes

In [222]:
### copy results back to master node
!aws s3 cp $S3DIR"/PEPS/"$BASE".vs.csv" $LOCALDIR"/"$BASE".vs.csv"

download: s3://variant-spark/GigaScience/Data/PEPS/all-snps-header_5_4_3_2_1.vs.csv to PEPS/Test/all-snps-header_5_4_3_2_1.vs.csv

In [223]:
# when rerunning 
#!aws s3 cp $S3DIR"/PEPS/"$BASE".pheno.csv" $LOCALDIR"/"$BASE".pheno.csv"
#!aws s3 cp $S3DIR"/PEPS/"$BASE".TruthSNP.csv" $LOCALDIR"/"$BASE".TruthSNP.csv"

In [224]:
import numpy as np
import pandas as pd
import sklearn

# read the top 100 VariantSpark output 
FullVSoutput = pd.read_csv(LOCALDIR+"/"+BASE+".vs.csv") # full dataset

snpData = FullVSoutput.copy(deep=True)
snpData = snpData.set_index('variable').T
snpData = snpData.drop('importance', axis=0)

snpData100 = pd.DataFrame(FullVSoutput)[:100].copy(deep=True)
snpData100 = snpData100.set_index('variable').T
snpData100 = snpData100.drop('importance', axis=0)

snpData100.head()

variable,21_19506651_G_A,9_79469334_T_C,12_76362129_C_T,12_20412031_A_T,7_71185237_G_A,8_4075279_G_A,5_11016111_G_T,3_60507811_G_T,17_35959746_G_A,1_53162156_C_A,...,2_76231009_C_A,15_37547903_C_A,4_60768061_A_C,4_119876232_G_T,15_40236372_G_A,19_34608021_A_T,7_22152629_A_G,1_86763477_T_C,8_37120185_G_A,7_20216348_C_T
HG00096,2.0,2.0,2.0,0.0,0.0,2.0,0.0,0.0,2.0,0.0,...,2.0,0.0,0.0,0.0,1.0,0.0,2.0,1.0,0.0,1.0
HG00097,2.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,...,0.0,2.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
HG00099,2.0,1.0,1.0,0.0,1.0,0.0,1.0,2.0,1.0,0.0,...,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0
HG00100,2.0,1.0,2.0,0.0,0.0,2.0,1.0,2.0,0.0,0.0,...,1.0,1.0,1.0,0.0,0.0,0.0,2.0,0.0,1.0,2.0
HG00101,1.0,2.0,1.0,0.0,1.0,2.0,2.0,1.0,2.0,1.0,...,0.0,2.0,1.0,1.0,0.0,0.0,2.0,0.0,1.0,0.0

In [225]:
# Read the label created by PEPS and used during VS training and join to data
label = pd.read_csv(LOCALDIR+"/"+BASE+".pheno.csv")
label.head()
jn=snpData.join(label.set_index('sample'))
jn100=snpData100.join(label.set_index('sample'))
jn100.head()

,21_19506651_G_A,9_79469334_T_C,12_76362129_C_T,12_20412031_A_T,7_71185237_G_A,8_4075279_G_A,5_11016111_G_T,3_60507811_G_T,17_35959746_G_A,1_53162156_C_A,...,15_37547903_C_A,4_60768061_A_C,4_119876232_G_T,15_40236372_G_A,19_34608021_A_T,7_22152629_A_G,1_86763477_T_C,8_37120185_G_A,7_20216348_C_T,lbl
HG00096,2.0,2.0,2.0,0.0,0.0,2.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,1.0,0.0,2.0,1.0,0.0,1.0,1
HG00097,2.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,...,2.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0
HG00099,2.0,1.0,1.0,0.0,1.0,0.0,1.0,2.0,1.0,0.0,...,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1
HG00100,2.0,1.0,2.0,0.0,0.0,2.0,1.0,2.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,2.0,0.0,1.0,2.0,1
HG00101,1.0,2.0,1.0,0.0,1.0,2.0,2.0,1.0,2.0,1.0,...,2.0,1.0,1.0,0.0,0.0,2.0,0.0,1.0,0.0,1

In [226]:
raw1000Genoms = pd.read_csv(PEPSINPUT+".csv")
raw1000Genoms.head()

,SNP,HG00096,HG00097,HG00099,HG00100,HG00101,HG00102,HG00103,HG00105,HG00106,...,NA21128,NA21129,NA21130,NA21133,NA21135,NA21137,NA21141,NA21142,NA21143,NA21144
0,1:15820:G:T,1,1,1,0,0,1,1,0,0,...,1,0,0,1,1,1,1,0,1,0
1,1:62777:A:T,1,1,0,1,1,2,0,1,1,...,1,0,0,1,2,2,1,2,1,1
2,1:63268:T:C,0,0,0,0,1,1,0,0,2,...,1,0,0,2,1,0,0,0,1,2
3,1:843405:A:G,1,1,0,0,2,1,0,1,2,...,1,0,0,2,0,0,0,0,1,1
4,1:1012483:G:T,0,2,2,2,2,2,1,2,2,...,1,1,1,2,0,2,1,1,1,1

In [227]:
snpDataTruthKeep = pd.read_csv(LOCALDIR+"/"+BASE+".TruthSNP.csv") # truth SNPs 
#snpDataTruthKeep['v'].replace({':': '_'},inplace=True, regex=True)
snpDataTruthKeep.columns=['SNP']
#snpDataTruthKeep.set_index('variable')
#snpDataTruthKeep['value']=1
snpDataTruthKeep.head()

                SNP
0  10:128809541:A:G
1  12:130740770:A:G
2  12:131131186:C:T
3   13:28892985:C:T
4   14:49960242:A:G

In [228]:
raw1000Genoms.shape

(17373, 2505)

In [229]:
snpDataTruthKeep.shape

(28, 1)

In [230]:
#raw1000Genoms.set_index('variable')
#raw1000Genoms.sort_index(inplace=True)
#snpDataTruthKeep.set_index('variable')
#snpDataTruthKeep.sort_index(inplace=True)
#snpDataTruthsub=raw1000Genoms.join(snpDataTruthKeep.set_index('SNP'))
#snpDataTruthsub=raw1000Genoms.where(raw1000Genoms.variable==snpDataTruthKeep.variable).notna()
#snpDataTruthsub.loc[snpDataTruthsub['value'] == 1]

In [231]:
#snpDataTruth.sort_index(inplace=True)
#snpDataTruthKeep.sort_index(inplace=True)
#snpDataTruthsub=snpDataTruth.loc[snpDataTruth['variable'].isin(snpDataTruthKeep)]
#snpDataTruthsub=raw1000Genoms.where(raw1000Genoms.variable==snpDataTruthKeep.variable).notna()
snpDataTruthsub = pd.merge(raw1000Genoms,snpDataTruthKeep, on=['SNP'], how='inner')
#snpDataTruthsub=raw1000Genoms.join(snpDataTruthKeep.set_index('variable'))
#snpDataTruthsub=snpDataTruthsub.loc[snpDataTruthsub['k'] == 1]
snpDataTruthsub['SNP'].replace({':': '_'},inplace=True, regex=True)
snpDataTruthsub=snpDataTruthsub.set_index('SNP').T
#snpDataTruthsub = snpDataTruthsub.drop('importance', axis=0)

#snpDataTruthsub.shape
snpDataTruthsub.head()

SNP,2_75815890_T_C,2_136827600_C_G,3_60507811_G_T,3_169355019_T_C,4_21622448_T_C,4_32192914_A_G,4_160997959_A_G,5_31869530_G_A,5_124084849_A_G,7_156114838_A_G,...,10_128809541_A_G,12_130740770_A_G,12_131131186_C_T,13_28892985_C_T,14_49960242_A_G,16_6495591_G_A,19_9114906_C_G,19_34608021_A_T,21_19506651_G_A,22_50067315_T_G
HG00096,0,2,0,1,1,1,2,2,2,0,...,1,2,0,0,0,0,1,0,2,1
HG00097,1,0,2,2,0,1,0,1,2,1,...,1,1,0,1,0,1,1,0,2,0
HG00099,0,1,2,1,2,2,1,2,2,1,...,2,2,0,2,1,1,0,1,2,1
HG00100,0,0,2,0,1,2,0,1,1,0,...,1,2,0,0,1,1,0,0,2,1
HG00101,0,0,1,1,0,2,0,0,1,0,...,0,2,0,2,1,2,0,0,1,0

In [232]:
# Read the label created by PEPS and used during VS training and join to data
jnAll=snpDataTruthsub.join(label.set_index('sample'))
jnAll.head()

,2_75815890_T_C,2_136827600_C_G,3_60507811_G_T,3_169355019_T_C,4_21622448_T_C,4_32192914_A_G,4_160997959_A_G,5_31869530_G_A,5_124084849_A_G,7_156114838_A_G,...,12_130740770_A_G,12_131131186_C_T,13_28892985_C_T,14_49960242_A_G,16_6495591_G_A,19_9114906_C_G,19_34608021_A_T,21_19506651_G_A,22_50067315_T_G,lbl
HG00096,0,2,0,1,1,1,2,2,2,0,...,2,0,0,0,0,1,0,2,1,1
HG00097,1,0,2,2,0,1,0,1,2,1,...,1,0,1,0,1,1,0,2,0,0
HG00099,0,1,2,1,2,2,1,2,2,1,...,2,0,2,1,1,0,1,2,1,1
HG00100,0,0,2,0,1,2,0,1,1,0,...,2,0,0,1,1,0,0,2,1,1
HG00101,0,0,1,1,0,2,0,0,1,0,...,2,0,2,1,2,0,0,1,0,1

In [233]:
#snpDataTruth = snpDataTruth.set_index('variable').T
#snpDataTruth = snpDataTruth.drop('importance', axis=0)
#snpDataTruth.head()

In [234]:
jn100.head()

,21_19506651_G_A,9_79469334_T_C,12_76362129_C_T,12_20412031_A_T,7_71185237_G_A,8_4075279_G_A,5_11016111_G_T,3_60507811_G_T,17_35959746_G_A,1_53162156_C_A,...,15_37547903_C_A,4_60768061_A_C,4_119876232_G_T,15_40236372_G_A,19_34608021_A_T,7_22152629_A_G,1_86763477_T_C,8_37120185_G_A,7_20216348_C_T,lbl
HG00096,2.0,2.0,2.0,0.0,0.0,2.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,1.0,0.0,2.0,1.0,0.0,1.0,1
HG00097,2.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,...,2.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0
HG00099,2.0,1.0,1.0,0.0,1.0,0.0,1.0,2.0,1.0,0.0,...,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1
HG00100,2.0,1.0,2.0,0.0,0.0,2.0,1.0,2.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,2.0,0.0,1.0,2.0,1
HG00101,1.0,2.0,1.0,0.0,1.0,2.0,2.0,1.0,2.0,1.0,...,2.0,1.0,1.0,0.0,0.0,2.0,0.0,1.0,0.0,1

In [235]:
#helper function to train dataset

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score

def RF_AUC(dfx, nTree):
    df = dfx.copy()
    features = df.columns[:-1]
    
    df['is_train'] = np.random.uniform(0, 1, len(df)) <= .75
    train, test = df[df['is_train']==True], df[df['is_train']==False]
    clf = RandomForestClassifier(n_jobs=2, n_estimators=nTree, random_state=0)
    clf.fit(train[features], train['lbl'])
    #clf.predict(test[features])
    prob = clf.predict_proba(test[features])
    y_true = test['lbl']
    y_scores = prob[:,1]
    return clf, roc_auc_score(y_true, y_scores)

In [236]:
from scipy.stats import sem
from statistics import mean 

numTree=500

AucTruthAr=[]
AucTruthAr100=[]

# run 5 times to get a feel for the variation
for i in range(0,5):
    clfTruth, AucTruth = RF_AUC(jnAll, nTree=numTree)
    AucTruthAr.append(AucTruth)
    clfTruth, AucTruth = RF_AUC(jn100, nTree=numTree)
    AucTruthAr100.append(AucTruth)

print("AUC Total                    : ", mean(AucTruthAr),"sem", sem(AucTruthAr) )
print("AUC VariantSpark 100         : ", mean(AucTruthAr100),"sem", sem(AucTruthAr100) )

AUC Total                    :  0.7427731431332678 sem 0.007674976688547618
AUC VariantSpark 100         :  0.7003592726668074 sem 0.004613436579131516

In [237]:
snpDataTruthKeep.columns=['variable']
snpDataTruthKeep['truth']=1
snpDataTruthKeep['variable'].replace({':': '_'},inplace=True, regex=True)
VScorrect = pd.merge(FullVSoutput[:100],snpDataTruthKeep, on=['variable'], how='inner')

print ("VS found ", VScorrect.shape[0]," out of ", snpDataTruthKeep.shape[0],"truth variables")

VS found  9  out of  28 truth variables

In [238]:
VScorrect = pd.merge(FullVSoutput,snpDataTruthKeep, on=['variable'], how='left')
VScorrect=VScorrect.fillna(0)
VScorrect.head()

,variable,importance,HG00096,HG00097,HG00099,HG00100,HG00101,HG00102,HG00103,HG00105,...,NA21129,NA21130,NA21133,NA21135,NA21137,NA21141,NA21142,NA21143,NA21144,truth
0,21_19506651_G_A,5.956928,2,2,2,2,1,1,1,1,...,1,1,1,0,0,2,1,0,1,1.0
1,9_79469334_T_C,4.659037,2,2,1,1,2,2,1,2,...,2,2,2,2,2,2,2,2,2,1.0
2,12_76362129_C_T,0.655880,2,2,1,2,1,1,1,2,...,0,0,0,1,1,0,1,0,1,0.0
3,12_20412031_A_T,0.652730,0,1,0,0,0,0,0,0,...,2,1,2,1,0,2,1,0,0,0.0
4,7_71185237_G_A,0.645579,0,1,1,0,1,1,1,2,...,1,1,1,0,0,0,1,0,1,0.0

In [239]:
from scipy import stats

stats.mannwhitneyu(VScorrect.importance[:100], VScorrect.truth[:100])

MannwhitneyuResult(statistic=882.0, pvalue=2.0241158356994545e-26)

In [246]:
# append rbo path to syspath
sys.path.append('/home/hadoop/src/rbo')
%load_ext autoreload
%autoreload 2

In [274]:
VScorrect.head()

,variable,importance,HG00096,HG00097,HG00099,HG00100,HG00101,HG00102,HG00103,HG00105,...,NA21129,NA21130,NA21133,NA21135,NA21137,NA21141,NA21142,NA21143,NA21144,truth
0,21_19506651_G_A,5.956928,2,2,2,2,1,1,1,1,...,1,1,1,0,0,2,1,0,1,1.0
1,9_79469334_T_C,4.659037,2,2,1,1,2,2,1,2,...,2,2,2,2,2,2,2,2,2,1.0
2,12_76362129_C_T,0.655880,2,2,1,2,1,1,1,2,...,0,0,0,1,1,0,1,0,1,0.0
3,12_20412031_A_T,0.652730,0,1,0,0,0,0,0,0,...,2,1,2,1,0,2,1,0,0,0.0
4,7_71185237_G_A,0.645579,0,1,1,0,1,1,1,2,...,1,1,1,0,0,0,1,0,1,0.0

In [275]:
snpDataTruthKeep.head()

           variable  truth
0  10_128809541_A_G      1
1  12_130740770_A_G      1
2  12_131131186_C_T      1
3   13_28892985_C_T      1
4   14_49960242_A_G      1

In [273]:
import rbo

#S = [1, 2, 3]; T = [1, 3, 2]
#rbo.RankingSimilarity(S, T).rbo()

v=rbo.RankingSimilarity(VScorrect.variable[:100].values, snpDataTruthKeep.variable.values).rbo()
print("Rank-biased-overlap ",v)

Rank-biased-overlap  0.0889588920296764

# Results

```
v1=10; v2=8; v3=6; v4=4; v5=2
AUC Total                    :  0.7186311759007349 sem 0.012392640730408109
AUC VariantSpark 100         :  0.7400257375096144 sem 0.016097212737146947

VS found  11  out of  57 truth variables
MannwhitneyuResult(statistic=1078.0, pvalue=5.352942586230578e-24)



v1=5; v2=4; v3=3; v4=2; v5=1

AUC Total                    :  0.7427731431332678 sem 0.007674976688547618
AUC VariantSpark 100         :  0.7003592726668074 sem 0.004613436579131516

VS found  9  out of  28 truth variables

MannwhitneyuResult(statistic=882.0, pvalue=2.0241158356994545e-26)
Rank-biased-overlap  0.0889588920296764

```

# +++++++++++++ Dont need the rest ++++++++++++++++

# Transform VS csv to VCF

In [2]:
from pyspark import SparkContext
sc = SparkContext()
import hail as hl
import varspark.hail as vshl
vshl.init(sc=sc)

using variant-spark jar at '/home/hadoop/biospark/lib/python3.6/site-packages/varspark/jars/variant-spark_2.11-0.3.0-SNAPSHOT-all.jar'
using hail jar at '/home/hadoop/biospark/lib/python3.6/site-packages/hail/hail-all-spark.jar'
using hail jar at /home/hadoop/biospark/lib/python3.6/site-packages/hail/hail-all-spark.jar
Running on Apache Spark version 2.4.4
SparkUI available at http://ip-172-31-35-120.ap-southeast-2.compute.internal:4040
Welcome to
     __  __     <>__
    / /_/ /__  __/ /
   / __  / _ `/ / /
  /_/ /_/\_,_/_/_/   version 0.2.16-6da0d3571629
LOGGING: writing to /home/hadoop/hail-20200113-0304-0.2.16-6da0d3571629.log

In [27]:
%%sh
## get the top 100 elements and transform to bed
tail -n +2 /home/hadoop/input-small_VS.csv  | head -n 100 \
    | gawk '{split($0,a,"_"); print a[1]"\t"a[2]-1"\t"a[2]}' | \
    sort -k1n -k2n > /home/hadoop/input-small_VS.bed
head /home/hadoop/input-small_VS.bed
wc -l /home/hadoop/input-small_VS.bed

1	7565677	7565678
1	18535254	18535255
1	22577936	22577937
1	92140325	92140326
1	113349346	113349347
1	239574660	239574661
2	1625090	1625091
2	3110757	3110758
2	53567632	53567633
2	71300515	71300516
100 /home/hadoop/input-small_VS.bed

In [28]:
%%sh
#uload bed file to S3
aws s3 cp /home/hadoop/input-small_VS.bed            s3://csiro-tb/home/bau04c/test/input-small_VS.bed

upload: ./input-small_VS.bed to s3://csiro-tb/home/bau04c/test/input-small_VS.bed

In [29]:
# reading the original vcf file into Hail
data = hl.import_vcf('s3://csiro-tb/home/bau04c/test/test.vcf',reference_genome='GRCh37')
data.count()

2020-01-13 03:36:35 Hail: INFO: Coerced sorted dataset

(162, 2504)

In [31]:
interval_table = hl.import_bed('s3://csiro-tb/home/bau04c/test/input-small_VS.bed', reference_genome='GRCh37')
filtered_data = data.filter_rows(hl.is_defined(interval_table[data.locus]))
filtered_data.count()

2020-01-13 03:36:51 Hail: INFO: Reading table with no type imputation
  Loading column 'f0' as type 'str' (user-specified)
  Loading column 'f1' as type 'int32' (user-specified)
  Loading column 'f2' as type 'int32' (user-specified)

2020-01-13 03:36:52 Hail: INFO: Coerced sorted dataset

(100, 2504)

In [32]:
hl.export_vcf(filtered_data, 's3://csiro-tb/home/bau04c/test/test_VS.vcf')

2020-01-13 03:37:07 Hail: INFO: Coerced sorted dataset
2020-01-13 03:37:08 Hail: INFO: merging 2 files totalling 1007.7K...
2020-01-13 03:37:08 Hail: INFO: while writing:
    s3://csiro-tb/home/bau04c/test/test_VS.vcf
  merge time: 127.413ms

In [34]:
%%sh
### to copy results back to master node
aws s3 cp s3://csiro-tb/home/bau04c/test/test_VS.vcf /home/hadoop/input-small_VS.vcf

download: s3://csiro-tb/home/bau04c/test/test_VS.vcf to ./input-small_VS.vcf